apiVersion: apps/v1
kind: deployment

metadata:
  name: app-deploy
  namespace: myspace
  labels:
    name: app-deploy

spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingupdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      name: myapp-pod
  template:
    #the pod that i'm going to deploy
    metadata:
      name: myapp-pod
      namespace: myspace
      labels:
        name: myapp-pod
      spec:
        containers:
        - name: myapp-container
          image: stackupiss/northwind-app:v2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env: 
          - name: DB_HOST
            value: mydb-svc.myspace.svc.cluster.local
          - name: INSTANCES_IP_ADDRESS
            valueFrom:
              fieldPath: status.podIP
          resources:
            request:
              cpu: "100m"

    

---

apiVersion: v1
kind: Service

metadata: 
  name: myapp-svc
  namespace: myspace
  labels:
    name: myapp-svc

spec:
  type: LoadBalancer
  selector:
    name: myapp-pod
  ports:
    - port: 80
      targetPort: 3000
  env:
    - name: DB_HOST
      value: mydb-svc.myspace.svc.cluster.local

