apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "weatherapp.fullname" . }}
  namespace: default
spec:
  selector:
    istio: ingressgateway #controller
  servers:
  - hosts: 
    - {{ .Values.getwayhostname }}
    port:
      number: {{ .Values.getwayport}}
      protocol: HTTP
      name: HTTP