apiVersion: v1
kind: apiVersion: v1
kind: Service
metadata:
  name: {{ include "weatherapp.fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: http
  selector:
    name: {{ include "weatherapp.name" }}
    instance: {{ .release.Name}}
